image: node:latest

cache:
  paths:
    - node_modules/
stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - dist
      - node_modules
  before_script:
    - yarn install
  script:
    - yarn run build:all
  only:
    - master

deploy_production:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - mkdir .ssh
    - echo "$PRODUCTION_PRIVATE_KEY" | base64 --decode > .ssh/id_rsa
    - sudo chown 644 .ssh/id_rsa
    - rsync -avz -e "ssh -i .ssh/id_rsa -p $PRODUCTION_PORT -o StrictHostKeyChecking=no" --progress dist/* $PRODUCTION_USER@$PRODUCTION_HOST:$PRODUCTION_PATH/
  environment:
    name: production
    url: https://radar.typoniels.de/
  only:
    - master